services:
  - type: web
    name: task-backend
    runtime: node
    plan: free
    branch: main
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        value: mysql://USER:PASS@HOST:PORT/DBNAME
